"""ext id

Revision ID: c853168efbfe
Revises: f8febbf9caa6
Create Date: 2025-06-09 12:28:16.076381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = 'c853168efbfe'
down_revision: Union[str, None] = 'f8febbf9caa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM project")
    op.add_column('project', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_project_external_id'), 'project', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_external_id'), table_name='project')
    op.drop_column('project', 'external_id')
    # ### end Alembic commands ###
