"""project files

Revision ID: f8febbf9caa6
Revises: 4dd8a6c2db98
Create Date: 2025-06-09 12:12:17.518874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = 'f8febbf9caa6'
down_revision: Union[str, None] = '4dd8a6c2db98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM project")
    op.add_column('project', sa.Column('rules_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('project', sa.Column('setup_script_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'setup_script_path')
    op.drop_column('project', 'rules_file_path')
    # ### end Alembic commands ###
